import { IDebtInquiresResponse } from 'src/infraestructure/service-clients/interface/mym.inquire.interface';
import * as inquireRequestStructure from './inquire-structure-request.json';
import * as paymentRequestStructure from './payment-structure-request.json';
import * as returnRequestStructure from './return-structure-request.json';
import * as inquireResponseStructure from './inquire-structure-response.json';
import * as paymentResponseStructure from './payment-structure-response.json';
import * as returnResponseStructure from './return-structure-response.json';
import * as extPaymentRequestStructure from './ext-payment-structure-request.json';
import * as extPaymentResponseStructure from './ext-payment-structure-response.json';
import * as extAnnulmentRequestStructure from './ext-annulment-structure-request.json';
import * as extAnnulmentResponseStructure from './ext-annulment-structure-response.json';
import {
	ScotiabankConsultDebtRequestDTO,
	ScotiabankPaymentRequestDTO,
	ScotiabankAnnulmentRequestDTO,
	ScotiabankReversalPaymentRequestDTO,
	ScotiabankReversalAnnulmentRequestDTO as ScotiabankReversalAnnulmentRequestDTO,
} from './scotiabank.requests.dto';
import {
	IScotiabankAnnulmentResponseDTO,
	IScotiabankConsultDebtResponseDTO,
	IScotiabankPaymentResponseDTO,
	IScotiabankReversalAnnulmentResponseDTO,
	IScotiabankReversalPaymentResponseDTO,
} from './scotiabank.responses.dto';
import { IPaymentResponse } from 'src/infraestructure/service-clients/interface/mym.payment.interface';

export enum InputEnum {
	INQUIRE = 'inquire',
	PAYMENT = 'payment',
	RETURN = 'return',
	EXT_PAYMENT = 'ext_payment',
	EXT_ANNULMENT = 'ext_annulment',
}

export const positions = [
	410, 475, 540, 605, 670, 735, 800, 865, 930, 995, 1060, 1125, 1190, 1255, 1320, 1385, 1450, 1515, 1580, 1645, 1710,
	1775, 1840, 1905, 1970, 2035, 2100, 2165, 2230, 2295, 2360, 2425, 2490, 2555, 2620, 2685, 2750, 2815, 2880, 2945,
	3010, 3075, 3140, 3205, 3270, 3335, 3400, 3465, 3530, 3595,
];

export const cutStringResult = (result: string, numberOfDocuments: number): string => {
	if (numberOfDocuments) return result.slice(0, positions[numberOfDocuments - 1]);
	else return result.slice(0, 410);
};

export const getInputValues = (input: string, type: InputEnum): any => {
	const obj = {};
	let structure: Array<{ id: string; start: number; end: number }> = [];
	switch (type) {
		case InputEnum.INQUIRE:
			structure = inquireRequestStructure;
			break;
		case InputEnum.PAYMENT:
			structure = paymentRequestStructure;
			break;
		case InputEnum.RETURN:
			structure = returnRequestStructure;
			break;
		case InputEnum.EXT_PAYMENT:
			structure = extPaymentRequestStructure;
			break;
		case InputEnum.EXT_ANNULMENT:
			structure = extAnnulmentRequestStructure;
			break;
	}
	structure.forEach(item => {
		obj[item.id] = input.slice(item.start - 1, item.end);
	});
	return obj;
};

export const setOutputValues = (input: any, type: InputEnum): string => {
	let output = '';
	let structure: Array<{ id: string; start: number; end: number; padleft?: boolean }> = [];
	switch (type) {
		case InputEnum.INQUIRE:
			structure = inquireResponseStructure;
			break;
		case InputEnum.PAYMENT:
			structure = paymentResponseStructure;
			break;
		case InputEnum.RETURN:
			structure = returnResponseStructure;
			break;
		case InputEnum.EXT_PAYMENT:
			structure = extPaymentResponseStructure;
			break;
		case InputEnum.EXT_ANNULMENT:
			structure = extAnnulmentResponseStructure;
			break;
	}
	structure.forEach(item => {
		let portion = String(input[item.id]);
		const MAX = 1 + (item.end - item.start);
		if (portion.length > MAX) {
			portion = portion.slice(0, MAX);
		} else if (portion.length < MAX) {
			if (!!item.padleft) {
				portion = Array(1 + (MAX - portion.length)).join(' ') + portion;
			} else {
				portion = portion + Array(1 + (MAX - portion.length)).join(' ');
			}
		}
		output += portion;
	});
	return output;
};

export const setConsultDebtResponse = (
	valueJson: ScotiabankConsultDebtRequestDTO,
	response: IDebtInquiresResponse,
): IScotiabankConsultDebtResponseDTO => {
	const temp = {
		'MESSAGE TYPE IDENTIFICATION': '0210',
		'PRIMARY BIT MAP': 'F22080010E808000',
		'SECONDARY BIT MAP': '0000000000000018',
		'CODIGO DE PROCESO': valueJson['CODIGO DE PROCESO'],
		MONTO: valueJson.MONTO,
		'FECHA Y HORA DE TRANSACCION': valueJson['FECHA Y HORA DE TRANSACCION'],
		TRACE: valueJson.TRACE,
		'FECHA DE CAPTURA': valueJson['FECHA DE CAPTURA'],
		'BIN ADQUIRIENTE': valueJson['BIN ADQUIRIENTE'],
		'RETRIEVAL REFERENCE - NUMBER': valueJson['RETRIEVAL REFERENCE NUMBER'],
		'AUTHORIZATION ID RESPONSE': '000000',
		'RESPONSE CODE': response ? '00' : '21',
		'TERMINAL ID': valueJson['TERMINAL ID'],
		'TRANSACTION CURRENCY CODE': valueJson['TRANSACTION CURRENCY CODE'],
		'DATOS RESERVADOS': valueJson['DATOS RESERVADOS'],
		'LONGITUD DEL CAMPO': '',
		'CODIGO DE FORMATO': '',
		'BIN PROCESADOR': '',
		'BIN ACREEDOR': '',
		'CODIGO PRODUCTO / SERVICIO': 'REC',
		AGENCIA: valueJson['CODIGO DE AGENCIA DEL RECAUDADOR'],
		'TIPO DE IDENTIFICACION': valueJson['TIPO DE DATO DE CONSULTA'],
		'NUMERO DE IDENTIFICACION': valueJson['DATO DE CONSULTA'],
		'NOMBRE DEL DEUDOR': response?.customerName || '',
		'NUMERO DE SERVICIOS DEVUELTOS': '01',
		'NUMERO DE OPERACIÓN DE COBRANZA': '000008133016',
		'INDICADOR SI HAY MAS DOCUMENTOS': '0',
		'TAMAÑO MAXIMO DE BLOQUE': '01000',
		'POSICION DEL ULTIMO DOCUMENTO': '000',
		'PUNTERO DE LA BASE DE DATOS': '0000000000',
		'ORIGEN DE RESPUESTA': '0',
		'CODIGO DE RESPUESTA': '000',
		'FILLER 1': '',
		'CODIGO DE PRODUCTO/SERVICIO': valueJson['CODIGO DE PRODUCTO/SERVICIO'],
		MONEDA: valueJson['TRANSACTION CURRENCY CODE'],
		'ESTADO DEL DEUDOR': response?.documents?.length > 0 ? 'M' : 'V',
		'MENSAJE 1 AL DEUDOR': `PENDIENTE ${valueJson['TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'}`,
		'MENSAJE 2 AL DEUDOR': '',
		'INDICADOR DE CRONOLOGIA': String(response.cronologicIndicator),
		'INDICADOR DE PAGOS VENCIDOS': '0',
		'RESTRICCION DE PAGO': '0',
		'DOCUMENTOS POR SERVICIO': `${response?.documents?.length || '0'}`,
		'FILLER 2': '',
		'TIPO DE SERVICIO 1': '',
		'NUMERO DE DOCUMENTO 1': '',
		'REFERENCIA DE LA DEUDA 1': '',
		'FECHA DE VENCIMIENTO 1': '',
		'IMPORTE MINIMO 1': '',
		'IMPORTE A TOTAL 1': '',
		'TIPO DE SERVICIO 2': '',
		'NUMERO DE DOCUMENTO 2': '',
		'REFERENCIA DE LA DEUDA 2': '',
		'FECHA DE VENCIMIENTO 2': '',
		'IMPORTE MINIMO 2': '',
		'IMPORTE A TOTAL 2': '',
		'TIPO DE SERVICIO 3': '',
		'NUMERO DE DOCUMENTO 3': '',
		'REFERENCIA DE LA DEUDA 3': '',
		'FECHA DE VENCIMIENTO 3': '',
		'IMPORTE MINIMO 3': '',
		'IMPORTE A TOTAL 3': '',
		'TIPO DE SERVICIO 4': '',
		'NUMERO DE DOCUMENTO 4': '',
		'REFERENCIA DE LA DEUDA 4': '',
		'FECHA DE VENCIMIENTO 4': '',
		'IMPORTE MINIMO 4': '',
		'IMPORTE A TOTAL 4': '',
		'TIPO DE SERVICIO 5': '',
		'NUMERO DE DOCUMENTO 5': '',
		'REFERENCIA DE LA DEUDA 5': '',
		'FECHA DE VENCIMIENTO 5': '',
		'IMPORTE MINIMO 5': '',
		'IMPORTE A TOTAL 5': '',
		'TIPO DE SERVICIO 6': '',
		'NUMERO DE DOCUMENTO 6': '',
		'REFERENCIA DE LA DEUDA 6': '',
		'FECHA DE VENCIMIENTO 6': '',
		'IMPORTE MINIMO 6': '',
		'IMPORTE A TOTAL 6': '',
		'TIPO DE SERVICIO 7': '',
		'NUMERO DE DOCUMENTO 7': '',
		'REFERENCIA DE LA DEUDA 7': '',
		'FECHA DE VENCIMIENTO 7': '',
		'IMPORTE MINIMO 7': '',
		'IMPORTE A TOTAL 7': '',
		'TIPO DE SERVICIO 8': '',
		'NUMERO DE DOCUMENTO 8': '',
		'REFERENCIA DE LA DEUDA 8': '',
		'FECHA DE VENCIMIENTO 8': '',
		'IMPORTE MINIMO 8': '',
		'IMPORTE A TOTAL 8': '',
		'TIPO DE SERVICIO 9': '',
		'NUMERO DE DOCUMENTO 9': '',
		'REFERENCIA DE LA DEUDA 9': '',
		'FECHA DE VENCIMIENTO 9': '',
		'IMPORTE MINIMO 9': '',
		'IMPORTE A TOTAL 9': '',
		'TIPO DE SERVICIO 10': '',
		'NUMERO DE DOCUMENTO 10': '',
		'REFERENCIA DE LA DEUDA 10': '',
		'FECHA DE VENCIMIENTO 10': '',
		'IMPORTE MINIMO 10': '',
		'IMPORTE A TOTAL 10': '',
		'TIPO DE SERVICIO 11': '',
		'NUMERO DE DOCUMENTO 11': '',
		'REFERENCIA DE LA DEUDA 11': '',
		'FECHA DE VENCIMIENTO 11': '',
		'IMPORTE MINIMO 11': '',
		'IMPORTE A TOTAL 11': '',
		'TIPO DE SERVICIO 12': '',
		'NUMERO DE DOCUMENTO 12': '',
		'REFERENCIA DE LA DEUDA 12': '',
		'FECHA DE VENCIMIENTO 12': '',
		'IMPORTE MINIMO 12': '',
		'IMPORTE A TOTAL 12': '',
		'TIPO DE SERVICIO 13': '',
		'NUMERO DE DOCUMENTO 13': '',
		'REFERENCIA DE LA DEUDA 13': '',
		'FECHA DE VENCIMIENTO 13': '',
		'IMPORTE MINIMO 13': '',
		'IMPORTE A TOTAL 13': '',
		'TIPO DE SERVICIO 14': '',
		'NUMERO DE DOCUMENTO 14': '',
		'REFERENCIA DE LA DEUDA 14': '',
		'FECHA DE VENCIMIENTO 14': '',
		'IMPORTE MINIMO 14': '',
		'IMPORTE A TOTAL 14': '',
		'TIPO DE SERVICIO 15': '',
		'NUMERO DE DOCUMENTO 15': '',
		'REFERENCIA DE LA DEUDA 15': '',
		'FECHA DE VENCIMIENTO 15': '',
		'IMPORTE MINIMO 15': '',
		'IMPORTE A TOTAL 15': '',
		'TIPO DE SERVICIO 16': '',
		'NUMERO DE DOCUMENTO 16': '',
		'REFERENCIA DE LA DEUDA 16': '',
		'FECHA DE VENCIMIENTO 16': '',
		'IMPORTE MINIMO 16': '',
		'IMPORTE A TOTAL 16': '',
		'TIPO DE SERVICIO 17': '',
		'NUMERO DE DOCUMENTO 17': '',
		'REFERENCIA DE LA DEUDA 17': '',
		'FECHA DE VENCIMIENTO 17': '',
		'IMPORTE MINIMO 17': '',
		'IMPORTE A TOTAL 17': '',
		'TIPO DE SERVICIO 18': '',
		'NUMERO DE DOCUMENTO 18': '',
		'REFERENCIA DE LA DEUDA 18': '',
		'FECHA DE VENCIMIENTO 18': '',
		'IMPORTE MINIMO 18': '',
		'IMPORTE A TOTAL 18': '',
		'TIPO DE SERVICIO 19': '',
		'NUMERO DE DOCUMENTO 19': '',
		'REFERENCIA DE LA DEUDA 19': '',
		'FECHA DE VENCIMIENTO 19': '',
		'IMPORTE MINIMO 19': '',
		'IMPORTE A TOTAL 19': '',
		'TIPO DE SERVICIO 20': '',
		'NUMERO DE DOCUMENTO 20': '',
		'REFERENCIA DE LA DEUDA 20': '',
		'FECHA DE VENCIMIENTO 20': '',
		'IMPORTE MINIMO 20': '',
		'IMPORTE A TOTAL 20': '',
		'TIPO DE SERVICIO 21': '',
		'NUMERO DE DOCUMENTO 21': '',
		'REFERENCIA DE LA DEUDA 21': '',
		'FECHA DE VENCIMIENTO 21': '',
		'IMPORTE MINIMO 21': '',
		'IMPORTE A TOTAL 21': '',
		'TIPO DE SERVICIO 22': '',
		'NUMERO DE DOCUMENTO 22': '',
		'REFERENCIA DE LA DEUDA 22': '',
		'FECHA DE VENCIMIENTO 22': '',
		'IMPORTE MINIMO 22': '',
		'IMPORTE A TOTAL 22': '',
		'TIPO DE SERVICIO 23': '',
		'NUMERO DE DOCUMENTO 23': '',
		'REFERENCIA DE LA DEUDA 23': '',
		'FECHA DE VENCIMIENTO 23': '',
		'IMPORTE MINIMO 23': '',
		'IMPORTE A TOTAL 23': '',
		'TIPO DE SERVICIO 24': '',
		'NUMERO DE DOCUMENTO 24': '',
		'REFERENCIA DE LA DEUDA 24': '',
		'FECHA DE VENCIMIENTO 24': '',
		'IMPORTE MINIMO 24': '',
		'IMPORTE A TOTAL 24': '',
		'TIPO DE SERVICIO 25': '',
		'NUMERO DE DOCUMENTO 25': '',
		'REFERENCIA DE LA DEUDA 25': '',
		'FECHA DE VENCIMIENTO 25': '',
		'IMPORTE MINIMO 25': '',
		'IMPORTE A TOTAL 25': '',
		'TIPO DE SERVICIO 26': '',
		'NUMERO DE DOCUMENTO 26': '',
		'REFERENCIA DE LA DEUDA 26': '',
		'FECHA DE VENCIMIENTO 26': '',
		'IMPORTE MINIMO 26': '',
		'IMPORTE A TOTAL 26': '',
		'TIPO DE SERVICIO 27': '',
		'NUMERO DE DOCUMENTO 27': '',
		'REFERENCIA DE LA DEUDA 27': '',
		'FECHA DE VENCIMIENTO 27': '',
		'IMPORTE MINIMO 27': '',
		'IMPORTE A TOTAL 27': '',
		'TIPO DE SERVICIO 28': '',
		'NUMERO DE DOCUMENTO 28': '',
		'REFERENCIA DE LA DEUDA 28': '',
		'FECHA DE VENCIMIENTO 28': '',
		'IMPORTE MINIMO 28': '',
		'IMPORTE A TOTAL 28': '',
		'TIPO DE SERVICIO 29': '',
		'NUMERO DE DOCUMENTO 29': '',
		'REFERENCIA DE LA DEUDA 29': '',
		'FECHA DE VENCIMIENTO 29': '',
		'IMPORTE MINIMO 29': '',
		'IMPORTE A TOTAL 29': '',
		'TIPO DE SERVICIO 30': '',
		'NUMERO DE DOCUMENTO 30': '',
		'REFERENCIA DE LA DEUDA 30': '',
		'FECHA DE VENCIMIENTO 30': '',
		'IMPORTE MINIMO 30': '',
		'IMPORTE A TOTAL 30': '',
		'TIPO DE SERVICIO 31': '',
		'NUMERO DE DOCUMENTO 31': '',
		'REFERENCIA DE LA DEUDA 31': '',
		'FECHA DE VENCIMIENTO 31': '',
		'IMPORTE MINIMO 31': '',
		'IMPORTE A TOTAL 31': '',
		'TIPO DE SERVICIO 32': '',
		'NUMERO DE DOCUMENTO 32': '',
		'REFERENCIA DE LA DEUDA 32': '',
		'FECHA DE VENCIMIENTO 32': '',
		'IMPORTE MINIMO 32': '',
		'IMPORTE A TOTAL 32': '',
		'TIPO DE SERVICIO 33': '',
		'NUMERO DE DOCUMENTO 33': '',
		'REFERENCIA DE LA DEUDA 33': '',
		'FECHA DE VENCIMIENTO 33': '',
		'IMPORTE MINIMO 33': '',
		'IMPORTE A TOTAL 33': '',
		'TIPO DE SERVICIO 34': '',
		'NUMERO DE DOCUMENTO 34': '',
		'REFERENCIA DE LA DEUDA 34': '',
		'FECHA DE VENCIMIENTO 34': '',
		'IMPORTE MINIMO 34': '',
		'IMPORTE A TOTAL 34': '',
		'TIPO DE SERVICIO 35': '',
		'NUMERO DE DOCUMENTO 35': '',
		'REFERENCIA DE LA DEUDA 35': '',
		'FECHA DE VENCIMIENTO 35': '',
		'IMPORTE MINIMO 35': '',
		'IMPORTE A TOTAL 35': '',
		'TIPO DE SERVICIO 36': '',
		'NUMERO DE DOCUMENTO 36': '',
		'REFERENCIA DE LA DEUDA 36': '',
		'FECHA DE VENCIMIENTO 36': '',
		'IMPORTE MINIMO 36': '',
		'IMPORTE A TOTAL 36': '',
		'TIPO DE SERVICIO 37': '',
		'NUMERO DE DOCUMENTO 37': '',
		'REFERENCIA DE LA DEUDA 37': '',
		'FECHA DE VENCIMIENTO 37': '',
		'IMPORTE MINIMO 37': '',
		'IMPORTE A TOTAL 37': '',
		'TIPO DE SERVICIO 38': '',
		'NUMERO DE DOCUMENTO 38': '',
		'REFERENCIA DE LA DEUDA 38': '',
		'FECHA DE VENCIMIENTO 38': '',
		'IMPORTE MINIMO 38': '',
		'IMPORTE A TOTAL 38': '',
		'TIPO DE SERVICIO 39': '',
		'NUMERO DE DOCUMENTO 39': '',
		'REFERENCIA DE LA DEUDA 39': '',
		'FECHA DE VENCIMIENTO 39': '',
		'IMPORTE MINIMO 39': '',
		'IMPORTE A TOTAL 39': '',
		'TIPO DE SERVICIO 40': '',
		'NUMERO DE DOCUMENTO 40': '',
		'REFERENCIA DE LA DEUDA 40': '',
		'FECHA DE VENCIMIENTO 40': '',
		'IMPORTE MINIMO 40': '',
		'IMPORTE A TOTAL 40': '',
		'TIPO DE SERVICIO 41': '',
		'NUMERO DE DOCUMENTO 41': '',
		'REFERENCIA DE LA DEUDA 41': '',
		'FECHA DE VENCIMIENTO 41': '',
		'IMPORTE MINIMO 41': '',
		'IMPORTE A TOTAL 41': '',
		'TIPO DE SERVICIO 42': '',
		'NUMERO DE DOCUMENTO 42': '',
		'REFERENCIA DE LA DEUDA 42': '',
		'FECHA DE VENCIMIENTO 42': '',
		'IMPORTE MINIMO 42': '',
		'IMPORTE A TOTAL 42': '',
		'TIPO DE SERVICIO 43': '',
		'NUMERO DE DOCUMENTO 43': '',
		'REFERENCIA DE LA DEUDA 43': '',
		'FECHA DE VENCIMIENTO 43': '',
		'IMPORTE MINIMO 43': '',
		'IMPORTE A TOTAL 43': '',
		'TIPO DE SERVICIO 44': '',
		'NUMERO DE DOCUMENTO 44': '',
		'REFERENCIA DE LA DEUDA 44': '',
		'FECHA DE VENCIMIENTO 44': '',
		'IMPORTE MINIMO 44': '',
		'IMPORTE A TOTAL 44': '',
		'TIPO DE SERVICIO 45': '',
		'NUMERO DE DOCUMENTO 45': '',
		'REFERENCIA DE LA DEUDA 45': '',
		'FECHA DE VENCIMIENTO 45': '',
		'IMPORTE MINIMO 45': '',
		'IMPORTE A TOTAL 45': '',
		'TIPO DE SERVICIO 46': '',
		'NUMERO DE DOCUMENTO 46': '',
		'REFERENCIA DE LA DEUDA 46': '',
		'FECHA DE VENCIMIENTO 46': '',
		'IMPORTE MINIMO 46': '',
		'IMPORTE A TOTAL 46': '',
		'TIPO DE SERVICIO 47': '',
		'NUMERO DE DOCUMENTO 47': '',
		'REFERENCIA DE LA DEUDA 47': '',
		'FECHA DE VENCIMIENTO 47': '',
		'IMPORTE MINIMO 47': '',
		'IMPORTE A TOTAL 47': '',
		'TIPO DE SERVICIO 48': '',
		'NUMERO DE DOCUMENTO 48': '',
		'REFERENCIA DE LA DEUDA 48': '',
		'FECHA DE VENCIMIENTO 48': '',
		'IMPORTE MINIMO 48': '',
		'IMPORTE A TOTAL 48': '',
		'TIPO DE SERVICIO 49': '',
		'NUMERO DE DOCUMENTO 49': '',
		'REFERENCIA DE LA DEUDA 49': '',
		'FECHA DE VENCIMIENTO 49': '',
		'IMPORTE MINIMO 49': '',
		'IMPORTE A TOTAL 49': '',
		'TIPO DE SERVICIO 50': '',
		'NUMERO DE DOCUMENTO 50': '',
		'REFERENCIA DE LA DEUDA 50': '',
		'FECHA DE VENCIMIENTO 50': '',
		'IMPORTE MINIMO 50': '',
		'IMPORTE A TOTAL 50': '',
	};
	response?.documents.forEach((document, index) => {
		temp[`TIPO DE SERVICIO ${index + 1}`] = '001';
		temp[`NUMERO DE DOCUMENTO ${index + 1}`] = document?.documentId || '';
		temp[`REFERENCIA DE LA DEUDA ${index + 1}`] = response?.customerIdentificationCode || '';
		temp[`FECHA DE VENCIMIENTO ${index + 1}`] = document?.expirationDate || '';
		temp[`IMPORTE MINIMO ${index + 1}`] = removePoint(document?.minimumAmount) || '';
		temp[`IMPORTE A TOTAL ${index + 1}`] = removePoint(document?.totalAmount) || '';
	});
	return temp;
};

export const setPaymentResponse = (
	valueJson: ScotiabankPaymentRequestDTO,
	response: IPaymentResponse,
): IScotiabankPaymentResponseDTO => {
	return {
		'MESSAGE TYPE IDENTIFICATION': '0210',
		'PRIMARY BIT MAP': 'F220848188E08000',
		'SECONDARY BIT MAP': '0000000000000018',
		'CODIGO DE PROCESO': valueJson['CODIGO DE PROCESO'],
		MONTO: valueJson.MONTO,
		'FECHA Y HORA DE TRANSACCION': valueJson['FECHA Y HORA DE TRANSACCION'],
		TRACE: valueJson.TRACE,
		'FECHA DE CAPTURA': valueJson['FECHA DE CAPTURA'],
		'IDENTIFICACION EMPRESA': valueJson['BIN ADQUIRIENTE'],
		'RETRIEVAL REFERENCE - NUMBER': valueJson['RETRIEVAL REFERENCE NUMBER'],
		'AUTHORIZATION ID RESPONSE': '4',
		'RESPONSE CODE': response ? '00' : '21',
		'TERMINAL ID': valueJson['TERMINAL ID'],
		'TRANSACTION CURRENCY CODE': valueJson['TRANSACTION CURRENCY CODE'],
		'DATOS RESERVADOS': valueJson['DATOS RESERVADOS'],
		'TAMAÑO DEL BLOQUE': '',
		'CODIGO DE FORMATO': '01',
		'BIN PROCESADOR': '000000',
		'CODIGO DE ACREEDOR': '000000',
		'CODIGO DE PRODUCTO/SERVICIO': 'REC',
		'CODIGO DE PLAZA DEL RECAUDADOR': '0000',
		'CODIGO DE AGENCIA DEL RECAUDADOR': valueJson['CODIGO DE AGENCIA DEL RECAUDADOR'],
		'TIPO DE DATO DE PAGO': valueJson['TIPO DE DATO DE PAGO'],
		'DATO DE PAGO': valueJson['DATO DE PAGO'],
		'CODIGO DE CIUDAD': valueJson['CODIGO DE CIUDAD'],
		'NUMERO DE OPERAC.COBRANZA': '4',
		'NUMERO DE OPERAC.ACREEDOR': response?.operationNumberCompany || '',
		'NUMERO DE PROD/SERV PAGAD.': valueJson['NUMERO DE PROD/SERV PAGADO'],
		'NUMERO TOTAL DE DOC PAGADO': valueJson['NUMERO TOTAL DE DOC PAGADO'],
		'FILLER 1': '',
		'ORIGEN DE RESPUESTA': '0',
		'CODIGO DE RESPUESTA EXTEND': '000',
		'DESCRIPC. DE LA RPTA APLICATIV': response ? 'TRANSACCION PROCESADA OK' : 'TRANSACCION NO PROCESADA',
		'NOMBRE DEL DEUDOR': response?.clientName || '',
		'RUC DEL DEUDOR': '',
		'RUC DEL ACREEDOR': '',
		'CODIGO DE ZONA DEL DEUDOR': '',
		'FILLER 2': '',
		'CODIGO DEL PROD/SERVICIO': '001',
		'DESCRIPC. DEL PROD.SERV': `RECAUDACION ${valueJson['TRANSACTION CURRENCY CODE'] === '604' ? 'SOL' : 'DOL'}`,
		'IMPORTE TOTAL POR PROD/SERV': valueJson['IMPORTE TOTAL X PROD/SERV'],
		'MENSAJE 1': `RECAUDACION ${valueJson['TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'}`,
		'MENSAJE 2': '',
		'NUMERO DE DOCUMENTOS': '01',
		'FILLER 3': '',
		'TIPO DE SERVICIO': '001',
		'DESCRIPCION DEL DOCUMENTO': 'Recibo de Servi',
		'NUMERO DEL DOCUMENTO': valueJson['NUMERO DE DOCUMENTO DE PAG'],
		'PERIODO DE COTIZACION': '',
		'TIPO DOC IDENTIDAD': '',
		'NUMERO DOCUMENTO IDENTIDAD': '',
		'FECHA DE EMISION': '00000000',
		'FECHA DE VENCIMIENTO': '',
		'IMPORTE PAGADO': valueJson['IMPORTE TOTAL X PROD/SERV'],
		'CODIGO DE CONCEPTO 1': '01',
		'IMPORTE CONCEPTO 1': valueJson['IMPORTE PAGADO DEL DOCUMENTO'],
		'CODIGO DE CONCEPTO 2': '00',
		'IMPORTE CONCEPTO 2': '00000000000',
		'CODIGO DE CONCEPTO 3': '00',
		'IMPORTE CONCEPTO 3': '00000000000',
		'CODIGO DE CONCEPTO 4': '00',
		'IMPORTE CONCEPTO 4': '00000000000',
		'CODIGO DE CONCEPTO 5': '00',
		'IMPORTE CONCEPTO 5': '00000000000',
		'INDICADOR DE FACTURACION': '0',
		'NUMERO DE FACTURA': '',
		'REFERENCIA DE LA DEUDA': valueJson['REFERENCIA DE LA DEUDA'],
		'FILLER 4': '',
	};
};

export const setAnnulmentResponse = (
	valueJson: ScotiabankAnnulmentRequestDTO,
	response: IPaymentResponse,
	isExpired = false,
): IScotiabankAnnulmentResponseDTO => {
	return {
		'MESSAGE TYPE IDENTIFICATION': '0210',
		'PRIMARY BIT MAP': 'F220848188E08000',
		'SECONDARY BIT MAP': '0000004000000018',
		'CODIGO DE PROCESO': valueJson['CODIGO DE PROCESO'],
		MONTO: valueJson.MONTO,
		'FECHA Y HORA DE TRANSACCION': valueJson['FECHA Y HORA DE TRANSACCION 1'],
		TRACE: valueJson['TRACE 1'],
		'FECHA DE CAPTURA': valueJson['FECHA DE CAPTURA'],
		'IDENTIFICACION EMPRESA': valueJson['FORWARD INSTITUTION CODE 1'],
		'RETRIEVAL REFERENCE - NUMBER': valueJson['RETRIEVAL REFERENCE NUMBER'],
		'AUTHORIZATION ID RESPONSE': '4',
		'RESPONSE CODE': response ? '00' : '21',
		'TERMINAL ID': valueJson['TERMINAL ID'],
		'TRANSACTION CURRENCY CODE': valueJson['TRANSACTION CURRENCY CODE'],
		'DATOS RESERVADOS': valueJson['DATOS RESERVADOS'],
		'DATOS DEL DOCUMENTO A EXTORNAR': '',
		'LONGITUD DE LA TRAMA': '',
		'CODIGO DE FORMATO': '',
		'BIN PROCESADOR': valueJson['BIN PROCESADOR'],
		'CODIGO DE ACREEDOR': valueJson['CODIGO DE ACREEDOR'],
		'CODIGO DE PRODUCTO/SERVICIO 1': valueJson['CODIGO DE PRODUCTO/SERVICIO'],
		'CODIGO DE PLAZA DEL RECAUDADOR': '',
		'CODIGO DE AGENCIA DEL RECAUDADOR': valueJson['CODIGO DE AGENCIA DEL RECAUDADOR'],
		'TIPO DE DATO DE PAGO': '',
		'DATO DE PAGO': '',
		'CODIGO DE CIUDAD': valueJson['CODIGO DE CIUDAD'],
		'NOMBRE DEL CLIENTE': '',
		'RUC DEL DEUDOR': '',
		'RUC DEL ACREEDOR': '',
		'NUMERO DE TRANS. DE COB.ORI': valueJson['NUMERO DE TRANS. DE COB.ORI'],
		'NUMERO OPE. ORIGINAL ACREED': '',
		'FILLER 1': '',
		'ORIGEN DE RESPUESTA': '0',
		'CODIGO DE RESPUESTA EXTEND': isExpired ? '080' : '000',
		'DESCRIPC DE LA RPTA APLICA': response ? 'TRANSACCION PROCESADA OK' : 'TRANSACCION NO PROCESADA',
		'CODIGO DE PRODUCTO/SERVICIO 2': '001',
		'DESCRIPC DEL PROD/SERVICIO': `RECAUDACION ${
			valueJson['TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'
		}`,
		'IMPORTE DEL PROD./SERVICIO': valueJson.MONTO.slice(valueJson.MONTO.length - 11, valueJson.MONTO.length),
		'MENSAJE 1 MARKETING': `RECAUDACION ${valueJson['TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'}`,
		'MENSAJE 2 MARKETING': '',
		'NUMERO DE DOCUMENTOS': '01',
		'FILLER 2': '',
		'TIPO DE DOCUMENTO/SERVICIO': valueJson['CODIGO DE SERVICIO'],
		'DESCRIPCION DEL DOCUMENTO': '',
		'NUMERO DE DOCUMENTO': '',
		'PERIODO DE COTIZACION': '',
		'TIPO DE DOC IDENTIDAD': '',
		'NRO DE DOC IDENTIDAD': '',
		'FECHA DE EMISION': '',
		'FECHA DE VENCIMIENTO': '',
		'IMPORTE ANULADO DEL DCTO.': valueJson.MONTO.slice(valueJson.MONTO.length - 11, valueJson.MONTO.length),
		'CODIGO DE CONCEPTO 1': '01',
		'IMPORTE CONCEPTO 1': valueJson.MONTO.slice(valueJson.MONTO.length - 11, valueJson.MONTO.length),
		'CODIGO DE CONCEPTO 2': '',
		'IMPORTE CONCEPTO 2': '',
		'CODIGO DE CONCEPTO 3': '',
		'IMPORTE CONCEPTO 3': '',
		'CODIGO DE CONCEPTO 4': '',
		'IMPORTE CONCEPTO 4': '',
		'CODIGO DE CONCEPTO 5': '',
		'IMPORTE CONCEPTO 5': '',
		'INDICADOR DE COMPROBANTE': '',
		'NUMERO DE FACTURA ANULADA': '',
		'REFERENCIA DE LA DEUDA': '',
		'FILLER 3': '',
	};
};

export const setReversalPaymentResponse = (
	valueJson: ScotiabankReversalPaymentRequestDTO,
	response: IPaymentResponse,
): IScotiabankReversalPaymentResponseDTO => {
	return {
		'MESSAGE TYPE IDENTIFICATION': '0410',
		'PRIMARY BIT MAP': 'B22080010E808000',
		'DE(01) SECONDARY BIT MAP': '0000000000000018',
		'DE(03) CODIGO DE PROCESO': valueJson['DE(03) CODIGO DE PROCESO'],
		'DE(04) MONTO': valueJson['DE(04) MONTO'],
		'DE(07) FECHA Y HORA DE TRANSACCION': valueJson['DE(07) FECHA Y HORA DE TRANSACCION'],
		'DE(11) TRACE': valueJson.TRACE,
		'DE(17) FECHA DE CAPTURA': valueJson['DE(17) FECHA DE CAPTURA'],
		'DE(32) IDENTIFICACION EMPRESA': valueJson['DE(32) BIN ADQUIRIENTE'],
		'DE(37) RETRIEVAL REFERENCE - NUMBER': valueJson['DE(37) RETRIEVAL REFERENCE -NUMBER'],
		'DE(38) AUTHORIZATION ID RESPONSE': '4',
		'DE(39) RESPONSE CODE': '00',
		'DE(41) TERMINAL ID': valueJson['DE(41) TERMINAL ID'],
		'DE(49) TRANSACTION CURRENCY CODE': valueJson['DE(49) TRANSACTION CURRENCY CODE'],
		'DE(124) DATOS RESERVADOS': valueJson['DE(124) DATOS RESERVADOS'],
		'TAMAÑO DEL BLOQUE': '',
		'CODIGO DE FORMATO': '01',
		'BIN PROCESADOR': '000000',
		'CODIGO DE ACREEDOR': '000000',
		'CODIGO DE PRODUCTO/SERVICIO': 'REC',
		'CODIGO DE PLAZA DEL RECAUDADOR': '0000',
		'CODIGO DE AGENCIA DEL RECAUDADOR': valueJson['CODIGO DE AGENCIA DEL RECAUDADOR'],
		'TIPO DE DATO DE PAGO': valueJson['TIPO DE DATO DE PAGO'],
		'DATO DE PAGO': valueJson['DATO DE PAGO'],
		'CODIGO DE CIUDAD': valueJson['CODIGO DE CIUDAD'],
		'NUMERO DE OPERAC.COBRANZA': '4',
		'NUMERO DE OPERAC.ACREEDOR ': response?.operationNumberCompany || '',
		'NUMERO DE PROD/SERV PAGAD.': valueJson['NUMERO DE PROD/SERV PAGAD.'],
		'NUMERO TOTAL DE DOC PAGAD.': valueJson['NUMERO TOTAL DE DOC PAGAD.'],
		'FILLER 1': '',
		'ORIGEN DE RESPUESTA': '0',
		'CODIGO DE RESPUESTA EXTEND': '000',
		'DESCRIPC. DE LA RPTA APLICATIV': 'TRANSACCION PROCESADA OK',
		'NOMBRE DEL DEUDOR': response?.clientName || '',
		'RUC DEL DEUDOR': '',
		'RUC DEL ACREEDOR': '',
		'CODIGO DE ZONA DEL DEUDOR': '',
		'FILLER 2': '',
		'CODIGO DEL PROD/SERVICIO': '001',
		'DESCRIPC. DEL PROD.SERV': `RECAUDACION ${valueJson['DE(49) TRANSACTION CURRENCY CODE'] === '604' ? 'SOL' : 'DOL'}`,
		'IMPORTE TOTAL POR PROD/SERV': valueJson['IMPORTE TOTAL X PROD/SERV'],
		'MENSAJE 1 ': `RECAUDACION ${valueJson['DE(49) TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'}`,
		'MENSAJE 2 ': '',
		'NUMERO DE DOCUMENTOS': '01',
		'FILLER 3': '',
		'TIPO DE SERVICIO': '001',
		'DESCRIPCION DEL DOCUMENTO': 'Recibo de Servi',
		'NUMERO DEL DOCUMENTO': valueJson['NUMERO DE DOCUMENTO DE PAG'],
		'PERIODO DE COTIZACION': '',
		'TIPO DOC IDENTIDAD': '',
		'NUMERO DOCUMENTO IDENTIDAD': '',
		'FECHA DE EMISION': '00000000',
		'FECHA DE VENCIMIENTO': '',
		'IMPORTE PAGADO': valueJson['IMPORTE TOTAL X PROD/SERV'],
		'CODIGO DE CONCEPTO1 ': '01',
		'IMPORTE CONCEPTO 1': valueJson['IMPORTE PAGADO DEL DOCTO'],
		'CODIGO DE CONCEPTO2': '00',
		'IMPORTE CONCEPTO 2': '00000000000',
		'CODIGO DE CONCEPTO 3': '00',
		'IMPORTE CONCEPTO 3': '00000000000',
		'CODIGO DE CONCEPTO 4': '00',
		'IMPORTE CONCEPTO 4': '00000000000',
		'CODIGO DE CONCEPTO 5': '00',
		'IMPORTE CONCEPTO 5': '00000000000',
		'INDICADOR DE FACTURACION': '0',
		'NUMERO DE FACTURA': '',
		'REFERENCIA DE LA DEUDA': valueJson['REFERENCIA DE LA DEUDA'],
		'FILLER 4': '',
	};
};

export const setReversalAnnulmentResponse = (
	valueJson: ScotiabankReversalAnnulmentRequestDTO,
	response: IPaymentResponse,
	isExpired = false,
): IScotiabankReversalAnnulmentResponseDTO => {
	return {
		'MESSAGE TYPE IDENTIFICATION': '0410',
		'PRIMARY BIT MAP': 'B22080010E808000',
		'DE(01) SECONDARY BIT MAP': '0000000000000018',
		'DE(03) CODIGO DE PROCESO': valueJson['DE(03) CODIGO DE PROCESO'],
		'DE(04) MONTO': valueJson['DE(04) MONTO'],
		'DE(07) FECHA Y HORA DE TRANSACCION': valueJson['DE(07) FECHA Y HORA DE TRANSACCION'],
		'DE(11) TRACE': valueJson['DE(11) TRACE'],
		'DE(17) FECHA DE CAPTURA': valueJson['DE(17) FECHA DE CAPTURA'],
		'DE(32) IDENTIFICACION EMPRESA': valueJson['FORWARD INSTITUTION CODE'],
		'DE(37) RETRIEVAL REFERENCE - NUMBER': valueJson['DE(37) RETRIEVAL REFERENCE -NUMBER'],
		'DE(38) AUTHORIZATION ID RESPONSE': '4',
		'DE(39) RESPONSE CODE': '00',
		'DE(41) TERMINAL ID': valueJson['DE(41) TERMINAL ID'],
		'DE(49) TRANSACTION CURRENCY CODE': valueJson['DE(49) TRANSACTION CURRENCY CODE'],
		'DE(124) DATOS RESERVADOS': valueJson['DE(124) DATOS RESERVADOS'],
		'LONGITUD DE LA TRAMA': '',
		'CODIGO DE FORMATO': '',
		'BIN PROCESADOR': valueJson['BIN PROCESADOR'],
		'CODIGO DE ACREEDOR': valueJson['CODIGO DE ACREEDOR'],
		'CODIGO DE PRODUCTO/SERVICIO 1': valueJson['CODIGO DE PRODUCTO/SERVICIO'],
		'CODIGO DE PLAZA DEL RECAUDADOR': '',
		'CODIGO DE AGENCIA DEL RECAUDADOR': valueJson['CODIGO DE AGENCIA DEL RECAUDADOR'],
		'TIPO DE DATO DE PAGO': '',
		'DATO DE PAGO': '',
		'CODIGO DE CIUDAD': valueJson['CODIGO DE CIUDAD'],
		'NOMBRE DEL CLIENTE': '',
		'RUC DEL DEUDOR': '',
		'RUC DEL ACREEDOR': '',
		'NUMERO DE TRANS. DE COB.ORI': valueJson['NUMERO DE TRANS. DE COB.ORI'],
		'NUMERO OPE. ORIGINAL ACREED': '',
		'FILLER 1': '',
		'ORIGEN DE RESPUESTA': '0',
		'CODIGO DE RESPUESTA EXTEND': '000',
		'DESCRIPC DE LA RPTA APLICA': 'TRANSACCION PROCESADA OK',
		'CODIGO DE PRODUCTO/SERVICIO 2': '001',
		'DESCRIPC DEL PROD/SERVICIO': `RECAUDACION ${
			valueJson['DE(49) TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'
		}`,
		'IMPORTE DEL PROD./SERVICIO': valueJson['DE(04) MONTO'].slice(
			valueJson['DE(04) MONTO'].length - 11,
			valueJson['DE(04) MONTO'].length,
		),
		'MENSAJE 1 MARKETING': `RECAUDACION ${
			valueJson['DE(49) TRANSACTION CURRENCY CODE'] === '604' ? 'SOLES' : 'DOLARES'
		}`,
		'MENSAJE 2 MARKETING': '',
		'NUMERO DE DOCUMENTOS': '01',
		'FILLER 2': '',
		'TIPO DE DOCUMENTO/SERVICIO': valueJson['TIPO DE SERVICIO'],
		'DESCRIPCION DEL DOCUMENTO': '',
		'NUMERO DE DOCUMENTO ': '',
		'PERIODO DE COTIZACION': '',
		'TIPO DE DOC IDENTIDAD ': '',
		'NRO DE DOC IDENTIDAD ': '',
		'FECHA DE EMISION': '',
		'FECHA DE VENCIMIENTO': '',
		'IMPORTE ANULADO DEL DCTO.': valueJson['DE(04) MONTO'].slice(
			valueJson['DE(04) MONTO'].length - 11,
			valueJson['DE(04) MONTO'].length,
		),
		'CODIGO DE CONCEPTO 1': '01',
		'IMPORTE CONCEPTO 1': valueJson['DE(04) MONTO'].slice(
			valueJson['DE(04) MONTO'].length - 11,
			valueJson['DE(04) MONTO'].length,
		),
		'CODIGO DE CONCEPTO 2': '',
		'IMPORTE CONCEPTO 2': '',
		'CODIGO DE CONCEPTO 3': '',
		'IMPORTE CONCEPTO 3': '',
		'CODIGO DE CONCEPTO 4': '',
		'IMPORTE CONCEPTO 4': '',
		'CODIGO DE CONCEPTO 5': '',
		'IMPORTE CONCEPTO 5': '',
		'INDICADOR DE COMPROBANTE': '',
		'NUMERO DE FACTURA ANULADA': '',
		'REFERENCIA DE LA DEUDA': '',
		'FILLER 3': '',
	};
};

export const removePoint = (num: string) => {
	const arr = num.split('');
	const position = arr.findIndex(n => n === '.');
	if (position) arr.splice(position, 1);
	return arr.join('');
};
