export enum EnumCurrency {
	USD = 'USD',
	PEN = 'PEN',
}

export const CurrencyDTO = {
	604: 'PEN',
	840: 'USD',
};

export const PaymentTypeDTO = {
	'00': 'EF',
	'01': 'EF',
	'02': 'CP',
	'03': 'CJ',
	'04': 'TD',
	'05': 'CT',
	'06': 'EF',
	'07': 'EF',
	'10': 'EF',
};

export const ScotiabankErrorCodes = [
	'DOCUMENTO SOLICITADO PARA EXTORNAR NO ENCONTRADO',
	'CONSULTA DE DEUDA REALIZADA PREVIAMENTE',
	'NO HAY DEUDAS DE CLIENTES REGISTRADAS',
	'NÚMERO DE REFERENCIA NO EXISTE',
	'TRANSACCIÓN REGISTRADA PREVIAMENTE',
	'MONTO TOTAL PAGADO NO COINCIDE CON MONTO PAGADO POR DOCUMENTO',
	'ERROR EN MONTO',
	'TOTAL AMOUNT ES MAYOR QUE LOS DOCUMENTOS PAGADOS',
	'AGOTADO EL TIEMPO PARA SOLICITAR EXTORNO',
	'DOCUMENTO YA FUE PAGADO',
	'AGOTADO EL TIEMPO PARA SOLICITAR EXTORNO',
];

export const ScotiabankOtherCodes = ['DOCUMENTO YA FUE PAGADO', 'CLIENTE SIN DEUDAS', 'EXTORNO REALIZADO'];
