export const responseConstants = {
	SUCCESS: {
		code: '0001',
		description: 'TRANSACCION REALIZADA CON EXITO',
	},
	'Error: Falta array de documentos pagados': {
		code: '3000',
		description: 'FORMATO DE TRAMA NO VALIDO',
	},
	TRANSACTION_INCOMPLETE: {
		code: '3002',
		description: 'NO SE PUDO REALIZAR LA TRANSACCION',
	},
	ANNULMENT_INCORRECT: {
		code: '3004',
		description: 'NO SE PUEDE REALIZAR EL REGISTRO DE EXTORNO',
	},
	'CLIENTE SIN DEUDAS': {
		code: '3009',
		description: 'NO TIENE DEUDAS PENDIENTES',
	},
	'NUMERO DE REFERENCIA NO EXISTE': {
		code: '0101',
		description: 'NUMERO DE REFERENCIA NO EXISTE',
	},
	'AGOTADO EL TIEMPO PARA SOLICITAR EXTORNO': {
		code: '0102',
		description: 'NUMERO DE REFERENCIA EXPIRADA',
	},
	'DOCUMENTO YA FUE PAGADO': {
		code: '0106',
		description: 'NUMERO DE REFERENCIA CON ESTADO PAGADO',
	},
	ERROR_PAY_OLDEST_DOCUMENT: {
		code: '0290',
		description: 'ERROR DEBE PAGAR LA CUOTA MAS ANTIGUA',
	},
	INVALID_REFERENCE: {
		code: '3013',
		description: 'ESTADO DE NRO DE REFERENCIA NO VALIDO',
	},
	'DOCUMENTO SOLICITADO PARA EXTORNAR NO ENCONTRADO': {
		code: '3014',
		description: 'EXTORNO NO PROCESADO PORQUE NO EXISTE REGISTRO DEL PAGO',
	},
	'MONTO TOTAL PAGADO NO COINCIDE CON MONTO PAGADO POR DOCUMENTO': {
		code: '3051',
		description: 'MONTO DE PAGO DEBE SER MINIMO O MAXIMO',
	},
	'TOTAL AMOUNT ES MAYOR QUE LOS DOCUMENTOS PAGADOS': {
		code: '3051',
		description: 'MONTO DE PAGO DEBE SER MINIMO O MAXIMO',
	},
	'ERROR EN MONTO': {
		code: '3051',
		description: 'MONTO DE PAGO DEBE SER MINIMO O MAXIMO',
	},
};
